apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openlegal-serving
resources:
  - ../serving
  - service-account.yaml
configMapGenerator:
  - name: openlegal-server-config
    behavior: replace
    files:
      - server.toml
  - name: openlegal-document-controller-config
    files:
      - kubeconfig
patches:
  - path: deployment-patch.yaml
