apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openlegal-serving
resources:
  - ../../config
  - job.yaml
# Apply this operation separately, after stopping serving; see deployment guide.
